version: "3"
services:
# hdfs / remote fs
  hdfs:
    image: gchq/hdfs:3.3
    command: namenode
    container_name: hdfs-namenode
    environment:
      - HADOOP_CONF_DIR=${HADOOP_CONF_DIR}
    ports:
      - 9870:9870
    volumes:
      - ./hdfs:${HADOOP_CONF_DIR}:ro
      - /var/log/hadoop
      - /data1
      - /data2

  hdfs-datanode:
    depends_on:
      - hdfs
    image: gchq/hdfs:3.3
    command: datanode
    container_name: hdfs-datanode
    environment:
      - HADOOP_CONF_DIR=${HADOOP_CONF_DIR}
    volumes:
      - ./hdfs:${HADOOP_CONF_DIR}:ro
      - /var/log/hadoop
      - /data1
      - /data2

# foundation db / catalog
  fdb:
    image: foundationdb/foundationdb:7.1.24
    ports:
      - "4550:4550"
    environment:
      FDB_NETWORKING_MODE: container
      FDB_COORDINATOR_PORT: 4550
      FDB_PORT: 4550
    container_name: fdb-0

# byconity:
  tso:
    image: byconity/byconity:latest
    command: bash -c "/etc/byconity/fdb/fdbcli -C /etc/byconity/fdb/fdb.cluster --exec \"configure new single ssd\"; tso-server --config-file /config/tso.yml"
    depends_on:
      - fdb
      - hdfs
    volumes:
      - "./byconity-simple-cluster/:/config/:ro"
      - "./fdb/:/etc/byconity/fdb/"
    # evironment:
    container_name: tso-0
    healthcheck:
      test:
        - CMD
        - curl
        - "tso-0:18845/status"
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_PTRACE

  server:
    image: byconity/byconity:latest
    command: bash -c "curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 tso-0:18845/status && clickhouse-server --config-file /config/server.yml"
    depends_on:
      - tso
      - hdfs
    ports:
      - "9000:52145"
      - "8123:21557"
    container_name: server-0
    volumes:
      - "./byconity-simple-cluster/:/config/:ro"
      - "./fdb/:/etc/byconity/fdb/"
    healthcheck:
      test:
        - CMD
        - curl
        - "server-0:21557/?query=SELECT%201"
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_PTRACE

  worker-write:
    image: byconity/byconity:latest
    command: bash -c "curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 server-0:21557 && clickhouse-server --config-file /config/worker.yml"
    depends_on:
      - server
    container_name: worker-write-0
    volumes:
      - "./byconity-simple-cluster/:/config/:ro"
      - "./fdb/:/etc/byconity/fdb/"
    healthcheck:
      test:
        - CMD
        - curl
        - "worker-write-0:21557/?query=SELECT%201"
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_PTRACE

  worker-default:
    image: byconity/byconity:latest
    command: bash -c "curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 server-0:21557 && clickhouse-server --config-file /config/worker.yml"
    depends_on:
      - server
    container_name: worker-default-0
    volumes:
      - "./byconity-simple-cluster/:/config/:ro"
      - "./fdb/:/etc/byconity/fdb/"
    healthcheck:
      test:
        - CMD
        - curl
        - "worker-default-0:21557/?query=SELECT%201"
      interval: 10s
      timeout: 5s
      retries: 5
    cap_add:
      - SYS_PTRACE

  daemon-manager:
    image: byconity/byconity:latest
    command: bash -c "curl --retry 10 --retry-delay 5 --retry-connrefused --retry-max-time 120 --max-time 120 server-0:21557 && daemon-manager --config-file ./config/daemon-manager.yml"
    depends_on:
      - server
    container_name: daemon-manager-0
    volumes:
      - "./byconity-simple-cluster/:/config/:ro"
      - "./fdb/:/etc/byconity/fdb/"
    healthcheck:
      test:
        - CMD
        - curl
        - "daemon-manager-0:17553/status"
      interval: 10s
      timeout: 5s
      retries: 5 
    cap_add:
      - SYS_PTRACE
